### ISSUE TITLE
KDDCUP-99 dataset discrepancy

### ISSUE THREAD

**Issue by temibabs** [danieltan07/dagmm#12]
The KDD-CUP dataset has 120 features according to the paper, the NPZ file in this repo contains 118 features. What's up?

**Comment by danieltan07** [comment]
The 120 features came from the complete dataset. I am only using the 10% subset where the other 2 features coming from a categorical variable is not there.

**Comment by yipala** [comment]
why if not use pretrain model ，the test code can get very high accuracy

**Comment by temibabs** [comment]
Okay, thanks.
